# Generated by Django 4.1 on 2022-10-16 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='suitable_for_diabetics',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='vegeterian',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.tag'),
        ),
    ]
